### ISSUE TITLE
Add projectsStopJobInstance

### ISSUE THREAD

**Issue by sgokaram-saagie** [saagie/gradle-saagie-dataops-plugin#52] opened 2019-08-02 03:03 UTC
Acceptance Criteria
https://github.com/saagie/gradle-saagie-dataops-plugin/wiki/projectsStopJobInstance

**Comment by youenchene** [comment] 2019-11-05 17:08
➜  test plugin gradle dataops gradle projectsStopJobInstance

> Task :projectsStopJobInstance FAILED
Something went wrong when stopping the job instance: {"errors":[{"message":"Unexpected error"}],"data":null}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectsStopJobInstance'.
> Something went wrong when stopping the job instance: {"errors":[{"message":"Unexpected error"}],"data":null}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by youenchene** [comment] 2019-11-05 17:08
project {
        id = '2438b9b6-a9ee-4816-bfa8-9ed89896dfb4'
    }

 /*
    job {
        id = 'e098ec6c-dd87-4ce7-b243-bddbc6fd0fab'
        //name = 'Test Job for the Boss 6'
        //description = 'Description'
        //technology = '13522063-c18b-4ecd-b61f-3bae1e0ad93c'
        //category = 'Extraction'
    }*/
    
    jobinstance {
        id = 'e28a85b2-cef3-4611-9e76-d5c360aa34ea'
    }

**Comment by DecampsRenan** [comment] 2019-11-13 15:06
Ok the problem is that we've got an API error if the id doesn't exists or if the jobinstance is already ended (success or killed)
But I can't tell the difference based on the API response; should I print a warning saying "Your job is already ended or doesn't exists" ?

**Comment by youenchene** [comment] 2019-11-14 11:34
Need Saagie product improvment to fix these.

Closing the issue.

**Comment by youenchene** [comment] 2019-11-14 11:35
Need Saagie improvement to get proper message error.

closing the issue.

**Closed by youenchene** 2019-11-14 11:35 UTC
Labels: PM Test Not Passing, enhancement
